<?php
/**
 * Created by PhpStorm.
 * User: astayart
 * Date: 4/11/14
 * Time: 3:05 PM
 */
$helper = Mage::helper('mdg_giftregistry');
//$sess = Mage::getSingleton('customer/session');
//$reg = $sess->getLoadedRegistry();
$reg = Mage::getSingleton('mdg_giftregistry/entity')->load($this->getRequest()->getParam('registry_id'));
?>
<?php if($reg): ?>
    <form action="<?php echo $this->getUrl('mdg_giftregistry/index/editPost/') ?>" method="post" id="form-validate">
        <fieldset>
            <?php echo $this->getBlockHtml('formkey') ?>
            <input type="hidden" id="type_id" value="<?php echo $reg->getTypeId() ?>" />
            <input type="hidden" id="registry_id" name="registry_id" value="<?php echo $reg->getId() ?>" />
            <ul class="form-list">
                <li class="field">
                    <label class="giftreg" for="event_name"><?php echo $this->__('Event Name') ?></label>
                    <input type="text"
                           name="event_name" id="event_name"
                           value="<?php echo $reg->getEventName() ?>"
                           title="<?php echo $this->__('Event Name') ?>" />
                </li>
                <li class="field">
                    <label class="giftreg" for="event_location"><?php echo $this->__('Event Location') ?></label>
                    <input type="text"
                           name="event_location" id="event_location"
                           value="<?php echo $reg->getEventLocation() ?>"
                           title="<?php echo $this->__('Event Location') ?>" />
                </li>
                <li class="field">
                    <label class="giftreg" for="event_country">
                        <?php echo $this->__('Event Country') ?>
                    </label>
                    <input type="text"
                           name="event_country"
                           value="<?php echo $reg->getEventCountry() ?>"
                           title="<?php echo $this->__('Event Country') ?>" />
                </li>
            </ul>
            <div class="buttons-set">
                <button type="submit" title="Save" class="button">
                    <span>
                        <span><?php echo $this->__('Save') ?></span>
                    </span>
                </button>
            </div>
        </fieldset>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        //]]>
    </script>
<?php else: ?>
    <h2>There has been an issue loading the registry!</h2>
<?php endif; ?>
