<?php
/**
 * Created by PhpStorm.
 * User: magentouser
 * Date: 4/28/14
 * Time: 2:46 PM
 * @var $this Mdg_Giftregistry_Block_Add
 */
$registries = $this->getCustomerRegistryCollection();

?>
<?php $_product = Mage::registry('current_product'); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<ul class="add-to-links">
    <?php if ($this->helper('wishlist')->isAllow()) : ?>
        <li><a href="<?php echo $_wishlistSubmitUrl ?>"
               onclick="productAddToCartForm.submitLight(this, this.href); return false;"
               class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
    <?php endif; ?>
    <?php
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
    ?>
    <?php if ($_compareUrl) : ?>
        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"
                                                class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
    <?php endif; ?>
    <?php if ($registries->count() > 0) : ?>
        <?php foreach ($registries as $reg) : ?>
            <li><span class="separator">|</span>
                <a href="<?php echo $this->getUrl('mdg_giftregistry/item/add/') . '?product_id=' . $_product->getId() . '&registry_id=' . $reg->getId() ?>"
                   class="link-wishlist"><?php echo $this->__('Add to ') . $reg->getEventName() ?></a>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>
